name: update readme

on: [ workflow_dispatch ]

jobs:
  profile-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: profile-updater
        uses: kumackey/profile-updater@main